Exhibits Bug fix
TAMULib/exhibits pull request #78
Opened 2024-01-05 19:33 UTC by qtamu

Downgraded the blacklight-spotlight gem to 3.3 to be able to use our custom wysiyg customization.  This was needed to test collection manifest.

2024-01-05 21:07 UTC, wwtamu approved these changes

2024-01-30 16:47 UTC, jmicah commented
@qtamu Could you resolve the conflicts listed in this PR?

2024-01-30 16:47 UTC, jmicah requested changes
Need conflicts resolved.

2024-02-01 16:35 UTC, jmicah approved these changes

2024-02-29 16:33 UTC, merged